#!/bin/bash
# Build sndys bridge as a static library for linking into Swift app.
#
# 1. Use mx --emit-c to get all M2 modules as one C file
# 2. Append our bridge wrapper that removes 'static' and provides
#    the flat C API that Swift calls
# 3. Compile to .o and archive as libsndys.a

set -e
cd "$(dirname "$0")"

echo "=== Generating C from Modula-2 ==="
mx compile BridgeEntry.mod --emit-c -o bridge_all.c \
  -I . \
  -I ../../m2audio/src \
  -I ../../m2wav/src \
  -I ../../m2math/src \
  -I ../../m2fft/src \
  -I ../../m2dct/src \
  -I ../../m2stats/src \
  -I ../../m2knn/src \
  -I ../../m2hmm/src \
  -I ../../m2kmeans/src

echo "=== Generating bridge wrapper ==="

# Create a C file that #includes the generated code (with static functions)
# then provides non-static wrapper functions for Swift
cat > sndys_combined.c << 'BRIDGE_EOF'
/* sndys_combined.c — generated M2 code + bridge wrappers.
 * Auto-generated by build_lib.sh. Do not edit. */

/* Pull in all the M2 generated code (static functions) */
#include "bridge_all.c"

/* Pull in the C shim files needed by m2audio and m2sys */
BRIDGE_EOF

# Now append the bridge functions that call into the static M2 functions.
# We need to match the exact signatures mx generated (with _high params).
cat >> sndys_combined.c << 'WRAPPER_EOF'

#include <string.h>
#include <stdlib.h>
#include "sndys_bridge.h"

/* ── M2 module initialization ──────────────────────────── */

static int g_sndys_inited = 0;

void sndys_init(void) {
    if (g_sndys_inited) return;
    KeyDetect_init();
    Chords_init();
    g_sndys_inited = 1;
}

/* ── Exported bridge functions ─────────────────────────── */

int32_t sndys_read_audio(const char *path, double **signal,
                          uint32_t *numSamples, uint32_t *sampleRate) {
    int ok = 0;
    void *sig = NULL;
    AudioIO_ReadAudio((char*)path, 255, &sig, numSamples, sampleRate, &ok);
    *signal = (double *)sig;
    return ok ? 1 : 0;
}

void sndys_free_signal(double *signal, uint32_t numSamples) {
    void *p = signal;
    AudioIO_FreeSignal(&p, numSamples);
}

void sndys_analyze_stats(const double *signal, uint32_t numSamples,
                          uint32_t sampleRate, SndysStats *result) {
    /* M2 StatsResult layout must match */
    AudioStats_Analyze((void*)signal, numSamples, sampleRate, (void*)result);
}

void sndys_detect_key(const double *signal, uint32_t numSamples,
                       uint32_t sampleRate,
                       char *keyName, uint32_t keyNameSize,
                       double *confidence) {
    char buf[32];
    memset(buf, 0, sizeof(buf));
    KeyDetect_DetectKey((void*)signal, numSamples, sampleRate,
                         buf, 31, confidence);
    strncpy(keyName, buf, keyNameSize - 1);
    keyName[keyNameSize - 1] = '\0';
}

int32_t sndys_detect_beats(const double *signal, uint32_t numSamples,
                            uint32_t sampleRate,
                            double *bpm, double *confidence) {
    void *feats = NULL;
    uint32_t nf = 0;
    int ok = 0;
    ShortFeats_ExtractFast((void*)signal, numSamples, sampleRate,
                            0.050, 0.025, &feats, &nf, &ok);
    if (!ok || nf <= 4) { *bpm = 0; *confidence = 0; return 0; }
    Beat_BeatExtract(feats, nf, 34, 0.025, bpm, confidence);
    ShortFeats_FreeFeatures(&feats, nf);
    return 1;
}

double sndys_beat_strength(const double *signal, uint32_t numSamples,
                            uint32_t sampleRate) {
    return Rhythm_BeatStrength((void*)signal, numSamples, sampleRate);
}

uint32_t sndys_detect_onsets(const double *signal, uint32_t numSamples,
                              uint32_t sampleRate, double sensitivity,
                              double *onsets, uint32_t maxOnsets) {
    uint32_t count = 0;
    /* DetectOnsets takes open array: onsets, onsets_high */
    Onset_DetectOnsets((void*)signal, numSamples, sampleRate, sensitivity,
                       onsets, maxOnsets - 1, &count);
    return count;
}

double *sndys_compute_spectrogram(const double *signal, uint32_t numSamples,
                                   uint32_t sampleRate,
                                   uint32_t *numFrames, uint32_t *numBins) {
    void *out = NULL;
    Spectro_ComputeSpectrogram((void*)signal, numSamples, sampleRate,
                                0.050, 0.025, &out, numFrames, numBins);
    return (double *)out;
}

void sndys_free_spectro(double *data, uint32_t numElements) {
    void *p = data;
    Spectro_FreeSpectro(&p, numElements);
}

double *sndys_compute_chromagram(const double *signal, uint32_t numSamples,
                                  uint32_t sampleRate, uint32_t *numFrames) {
    void *out = NULL;
    Spectro_ComputeChromagram((void*)signal, numSamples, sampleRate,
                               0.050, 0.025, &out, numFrames);
    return (double *)out;
}

void sndys_free_chroma(double *data, uint32_t numFrames) {
    void *p = data;
    Spectro_FreeSpectro(&p, numFrames * 12);
}

void sndys_track_pitch(const double *signal, uint32_t numSamples,
                        uint32_t sampleRate,
                        double **pitches, double **times,
                        uint32_t *numFrames) {
    void *p = NULL, *t = NULL;
    PitchTrack_TrackPitch((void*)signal, numSamples, sampleRate, 5,
                           &p, &t, numFrames);
    *pitches = (double *)p;
    *times = (double *)t;
}

void sndys_free_pitch(double *pitches, double *times, uint32_t numFrames) {
    void *p = pitches, *t = times;
    PitchTrack_FreePitch(&p, &t, numFrames);
}

SndysChord *sndys_detect_chords(const double *signal, uint32_t numSamples,
                                 uint32_t sampleRate, uint32_t *numChords) {
    void *chroma = NULL;
    uint32_t chromaFrames = 0;
    void *chords = NULL;
    Spectro_ComputeChromagram((void*)signal, numSamples, sampleRate,
                               0.050, 0.025, &chroma, &chromaFrames);
    if (chromaFrames == 0) { *numChords = 0; return NULL; }
    Chords_DetectChordSequence(chroma, chromaFrames, &chords, numChords);
    Spectro_FreeSpectro(&chroma, chromaFrames * 12);
    return (SndysChord *)chords;
}

void sndys_free_chords(SndysChord *chords, uint32_t numChords) {
    void *p = chords;
    Chords_FreeChords(&p, numChords);
}

SndysNote *sndys_transcribe(const double *signal, uint32_t numSamples,
                              uint32_t sampleRate, uint32_t *numNotes) {
    void *notes = NULL;
    NoteTranscribe_Transcribe((void*)signal, numSamples, sampleRate,
                               &notes, numNotes);
    return (SndysNote *)notes;
}

void sndys_free_notes(SndysNote *notes, uint32_t numNotes) {
    void *p = notes;
    NoteTranscribe_FreeNotes(&p, numNotes);
}

void sndys_voice_features(const double *signal, uint32_t numSamples,
                            uint32_t sampleRate,
                            const double *pitches, uint32_t numPitchFrames,
                            SndysVoice *result) {
    uint32_t winSamp = (uint32_t)(0.050 * sampleRate);
    if (numSamples < winSamp) { memset(result, 0, sizeof(*result)); return; }

    /* Formants: analyze first frame only */
    VoiceFeats_ComputeFormants((void*)signal, winSamp, sampleRate,
                                &result->f1, &result->f2, &result->f3);

    /* Jitter/Shimmer: only practical for short signals (<30s) */
    if (pitches && numPitchFrames >= 2 && numSamples < sampleRate * 30) {
        result->jitter = VoiceFeats_ComputeJitter((void*)pitches, numPitchFrames);
        result->shimmer = VoiceFeats_ComputeShimmer((void*)signal, numSamples,
                                                      sampleRate,
                                                      (void*)pitches, numPitchFrames);
    } else {
        result->jitter = 0; result->shimmer = 0;
    }

    /* HNR: O(N*maxLag) — limit to first 5 seconds for large files */
    uint32_t hnrSamples = numSamples;
    if (hnrSamples > sampleRate * 5) { hnrSamples = sampleRate * 5; }
    result->hnr = VoiceFeats_ComputeHNR((void*)signal, hnrSamples, sampleRate);
}

void sndys_harmonic(const double *signal, uint32_t frameLen,
                     uint32_t sampleRate, double *hr, double *f0) {
    Harmonic_ComputeHarmonicF0((void*)signal, frameLen, sampleRate, hr, f0);
}

double *sndys_extract_features(const double *signal, uint32_t numSamples,
                                uint32_t sampleRate, uint32_t *numFrames) {
    void *feats = NULL;
    int ok = 0;
    ShortFeats_ExtractFast((void*)signal, numSamples, sampleRate,
                            0.050, 0.025, &feats, numFrames, &ok);
    if (!ok) { *numFrames = 0; return NULL; }
    return (double *)feats;
}

void sndys_free_features(double *feats, uint32_t numFrames) {
    void *p = feats;
    ShortFeats_FreeFeatures(&p, numFrames);
}

static char g_feat_name_buf[64];
const char *sndys_feature_name(uint32_t idx) {
    memset(g_feat_name_buf, 0, sizeof(g_feat_name_buf));
    ShortFeats_FeatureName(idx, g_feat_name_buf, 63);
    return g_feat_name_buf;
}

WRAPPER_EOF

echo "=== Compiling to object file ==="
clang -c sndys_combined.c -o sndys_combined.o \
  -I. -I../../m2audio/src \
  -I/opt/homebrew/include \
  -D_THREAD_SAFE \
  -O2 -arch arm64

echo "=== Renaming M2 main to avoid conflict with Swift ==="
llvm-objcopy --redefine-sym _main=_m2_bridge_main sndys_combined.o

echo "=== Creating static library ==="
# Also need m2sys.c
clang -c ~/.mx/lib/m2sys/m2sys.c -o m2sys.o -I/opt/homebrew/include -O2 -arch arm64
# And ax_bridge.c for SDL2 audio
clang -c ../../m2audio/src/ax_bridge.c -o ax_bridge.o \
  -I/opt/homebrew/include -D_THREAD_SAFE -O2 -arch arm64

ar rcs libsndys.a sndys_combined.o m2sys.o ax_bridge.o

echo "=== Done: libsndys.a ==="
ls -la libsndys.a
nm libsndys.a | grep " T _sndys_" | head -20
